# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf79dddfd430569f20bd256dc70a7bf4c706e2fa9629631e98bb9d5e11fa9add86e6e2d16562f1be49237c1202d9c99cfd263eadd08953cae2056af5c4cb968a

test:
  secret_key_base: d044dfa57fd811c4917f217a03e3bb41a612683b9d47a370381fa9358c289b7c3c284b4a85a442e7336cdda8a1acb3bc3f99d3f59c05d72c02c706dd52c610f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
